In [2]:
# BalanceSheet in Cleaned Data 
import pandas as pd
import numpy as np

In [4]:
import os

df=pd.read_csv(r"D:\BTP Project\data\clean\fact_balance_sheet.csv")
df

,symbol,year_id,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_assets,total_assets,debt_to_equity,equity_ratio,book_value_per_share
0,ABB,10,21.0,626,0,260,907,109,1,0,798,907,0.000000,0.713341,308.095238
1,ABB,16,21.0,767,0,351,1139,98,1,0,1040,1139,0.000000,0.691835,375.238095
2,ABB,21,21.0,916,0,436,1374,96,4,0,1274,1374,0.000000,0.681951,446.190476
3,ABB,26,21.0,1174,0,421,1616,108,3,0,1505,1616,0.000000,0.739480,569.047619
4,ABB,31,21.0,1366,0,679,2066,110,6,0,1950,2066,0.000000,0.671346,660.476190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,TATAMOTORS,47,766.0,54481,142131,144193,341570,138708,20964,24620,157278,341570,2.572646,0.161744,144.248042
1221,TATAMOTORS,51,766.0,43795,146449,138051,329061,138855,10251,29380,150575,329061,3.286484,0.135419,116.347258
1222,TATAMOTORS,55,766.0,44556,134113,155239,334674,132080,14274,26379,161941,334674,2.959115,0.135421,118.334204
1223,TATAMOTORS,61,766.0,84152,107262,177340,369521,121285,35698,22971,189566,369521,1.263124,0.229806,221.718016
1224,TATAMOTORS,62,736.0,100326,106549,183045,390656,157718,15526,33381,184031,390656,1.054293,0.258698,274.625000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1225 entries, 0 to 1224
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   symbol                1225 non-null   str
 1   year_id               1225 non-null   int64
 2   equity_capital        1225 non-null   float64
 3   reserves              1225 non-null   int64
 4   borrowings            1225 non-null   int64
 5   other_liabilities     1225 non-null   int64
 6   total_liabilities     1225 non-null   int64
 7   fixed_assets          1225 non-null   int64
 8   cwip                  1225 non-null   int64
 9   investments           1225 non-null   int64
 10  other_assets          1225 non-null   int64
 11  total_assets          1225 non-null   int64
 12  debt_to_equity        1225 non-null   float64
 13  equity_ratio          1224 non-null   float64
 14  book_value_per_share  1127 non-null   float64
dtypes: float64(4), int64(10), str(1)
memory usage: 143.7 KB

### Debt-to-Equity

$$
\text{Debt-to-Equity Ratio}
=
\frac{\text{Borrowings}}
{\text{Equity Capital} + \text{Reserves}}
$$

In [16]:
# Sort  debt_to_equity  low to high with the comapany name and year
df_sorted = df.sort_values(by='debt_to_equity', ascending=True)
df_sorted = df_sorted[['symbol', 'year_id', 'debt_to_equity']]
# make the symbol unique and get the latest year for each symbol
df_sorted = df_sorted.drop_duplicates(subset=['symbol'], keep='last')
df_sorted.head(50)

          symbol  year_id  debt_to_equity
954      SBILIFE       47        0.000000
165   BAJAJHLDNG       43        0.006051
853       JIOFIN       55        0.006511
653          ITC       16        0.008885
342     DIVISLAB       39        0.015236
1043     SIEMENS       62        0.018168
81     AMBUJACEM       44        0.020697
724       NAUKRI       43        0.035080
389    EICHERMOT       13        0.040876
530   HINDUNILVR       31        0.041074
233     BOSCHLTD       10        0.041270
501   HEROMOTOCO       16        0.050507
635        IRCTC       51        0.056150
882   PIDILITIND       12        0.067232
7            ABB       43        0.071987
498     HDFCLIFE       55        0.073116
744       MARUTI       16        0.093227
1167         TCS       43        0.097164
612         INFY       55        0.110056
555      ICICIGI       31        0.124327
111   ASIANPAINT       62        0.139592
457      HCLTECH       43        0.155773
144   BAJAJ-AUTO       62        0.169308
769         LTIM       12        0.174757
782           LT       12        0.174757
567   ICICIPRULI       26        0.193312
317    COALINDIA       43        0.200081
1186       TECHM       12        0.254331
1147  TATACONSUM       12        0.288773
998        WIPRO       34        0.290045
1071   SUNPHARMA       21        0.350885
232         BHEL       62        0.377206
977     SHREECEM       35        0.382488
300        CIPLA       26        0.451680
704    NESTLEIND       13        0.502111
323        DABUR       12        0.549403
401         GAIL       12        0.572064
375      DRREDDY       12        0.578113
448          HAL       61        0.618090
672         ONGC       43        0.631255
463      HAVELLS       12        0.680999
987       ZOMATO       42        0.713348
1088  ULTRACEMCO       39        0.750704
418     GODREJCP       31        0.754621
365        DMART       26        0.783695
936     RELIANCE       26        0.840894
703         NHPC       62        0.852076
268    BRITANNIA       51        0.969898
959    ZYDUSLIFE       11        0.991168
92    APOLLOHOSP       39        1.101680

In [17]:
# from last 10 companies 
df_sorted.tail(10)

          symbol  year_id  debt_to_equity
644         IRFC       35        9.621338
126     AXISBANK       39       10.501106
876          PFC       43       12.076134
898          PNB       26       12.122088
183   BANKBARODA       16       16.301768
280        CANBK       47       17.000449
1062   UNIONBANK       35       18.056748
43    ADANIGREEN       51       20.211171
65    ADANIPOWER       35       59.431946
808         LICI       39      332.593827

### Equity Ratio

$$
\text{Equity Ratio}
=
\frac{\text{Equity Capital} + \text{Reserves}}
{\text{Total Assets}}
$$

In [18]:
# Now the same for equity_ratio
df_sorted_equity = df.sort_values(by='equity_ratio', ascending=True)
df_sorted_equity = df_sorted_equity[['symbol', 'year_id', 'equity_ratio']]
# make the symbol unique and get the latest year for each symbol
df_sorted_equity = df_sorted_equity.drop_duplicates(subset=['symbol'], keep='last')
df_sorted_equity.head(50)

          symbol  year_id  equity_ratio
814         LICI       62      0.017072
565   ICICIPRULI       16      0.053796
949      SBILIFE       26      0.056731
273        CANBK       16      0.060221
497     HDFCLIFE       51      0.067671
1068   UNIONBANK       61      0.069614
193   BANKBARODA       61      0.072344
128     AXISBANK       47      0.103490
549    ICICIBANK       55      0.109522
482     HDFCBANK       39      0.118868
645         IRFC       39      0.121140
593   INDUSINDBK       26      0.123837
148   BAJAJFINSV       26      0.130821
293     CHOLAFIN       51      0.142693
872          PFC       26      0.145733
924       RECLTD       31      0.160151
825    KOTAKBANK       55      0.180220
38    ADANIGREEN       31      0.195292
906          PNB       61      0.206340
554      ICICIGI       26      0.206494
1029  SHRIRAMFIN       55      0.206636
177   BAJFINANCE       47      0.215303
1210   TATAPOWER       61      0.232687
767           MM       61      0.281993
1213  TATAMOTORS       16      0.300349
208   BHARTIARTL       16      0.329249
836     JSWSTEEL       51      0.342505
919    POWERGRID       62      0.360604
32      ADANIENT       43      0.361536
1099    TVSMOTOR       31      0.361782
739    MOTHERSON       51      0.369451
257         BPCL       61      0.373657
807        LODHA       62      0.383750
618          IOC       26      0.388322
1182   TATASTEEL       51      0.405220
310    COALINDIA       12      0.436752
59    ADANIPORTS       62      0.453724
678         NTPC       12      0.454423
524     HINDALCO       61      0.460058
705    NESTLEIND       17      0.487457
1133  TORNTPHARM       62      0.497349
431       GRASIM       31      0.500215
694         NHPC       26      0.503685
72    ADANIPOWER       62      0.505073
205          BEL       61      0.521739
224         BHEL       31      0.524960
637        IRCTC       61      0.530291
941     RELIANCE       47      0.530407
1137       TITAN       26      0.552980
86    APOLLOHOSP       12      0.570627

In [19]:
df_sorted_equity.tail(10)

          symbol  year_id  equity_ratio
1164         TCS       31      0.842485
659          ITC       43      0.844291
141   BAJAJ-AUTO       51      0.850417
725       NAUKRI       47      0.857597
346     DIVISLAB       55      0.885061
369        DMART       43      0.917522
989       ZOMATO       50      0.952560
853       JIOFIN       55      0.992952
164   BAJAJHLDNG       39      0.997927
13    ADANIENSOL       16           NaN

### Book Value per Share

$$
\text{Book Value per Share}
=
\frac{\text{Equity}}
{\dfrac{\text{Equity Capital}}{\text{Face Value}}}
$$

In [20]:
# now the same thing for Book value per share
df_sorted_book_value = df.sort_values(by='book_value_per_share', ascending=True)
df_sorted_book_value = df_sorted_book_value[['symbol', 'year_id', 'book_value_per_share']]
# make the symbol unique and get the latest year for each symbol
df_sorted_book_value = df_sorted_book_value.drop_duplicates(subset=['symbol'], keep='last')
df_sorted_book_value.head(30)

          symbol  year_id  book_value_per_share
206          BEL       62              8.272727
119         ATGL       62             35.554545
651         IRFC       62             39.379448
703         NHPC       62             39.969139
716    NESTLEIND       62             41.562500
629        IRCTC       26             54.200000
335        DABUR       62             58.542373
734    MOTHERSON       31             59.085714
664          ITC       62             60.164668
46    ADANIGREEN       62             66.767677
497     HDFCLIFE       51             73.894936
576   ICICIPRULI       62             80.152355
1182   TATASTEEL       51             93.728911
1211   TATAPOWER       62            105.250000
475      HAVELLS       62            123.714286
905          PNB       55            129.621302
1120       TRENT       62            130.000000
1144       TITAN       55            133.157303
915    POWERGRID       47            133.669725
274        CANBK       21            136.808421
222         BHEL       21            139.620408
72    ADANIPOWER       62            145.071299
418     GODREJCP       31            155.941176
322    COALINDIA       62            156.087944
852    JSWENERGY       62            160.292264
958      SBILIFE       62            162.265469
894   PIDILITIND       62            170.882353
690         NTPC       62            173.529958
24    ADANIENSOL       62            174.729392
213   BHARTIARTL       39            178.646823

In [22]:
df_sorted_book_value.tail(25)

          symbol  year_id  book_value_per_share
400    EICHERMOT       62            702.925926
603         INFY       16            778.496503
601   INDUSINDBK       61            807.159383
512   HEROMOTOCO       62            950.550000
144   BAJAJ-AUTO       62           1110.358423
945     RELIANCE       62           1211.133609
439       GRASIM       62           1386.835821
181   BAJFINANCE       62           1400.048387
794           LT       62           1405.000000
11           ABB       61           1761.428571
755       MARUTI       62           2838.407643
580       INDIGO       26           3235.000000
729       NAUKRI       62           3239.379845
245     BOSCHLTD       62           4246.000000
170   BAJAJHLDNG       62           5389.459459
984     SHREECEM       62           5799.722222
853       JIOFIN       55         570600.000000
971    ZYDUSLIFE       60                   NaN
992       ZOMATO       60                   NaN
1005       WIPRO       60                   NaN
1018        VEDL       60                   NaN
1056    UNITDSPR       60                   NaN
1068   UNIONBANK       61                   NaN
1094  ULTRACEMCO       62                   NaN
1107    TVSMOTOR       62                   NaN